Additional explanation of the sudoko solver

Sudoku solver

- how to represent the grid? x
- how to print the solution x
- is it possible to put a number on an empty square?
    possible(y,x,n) returns true if it is possible to put n on grid[y][x]
    false, otherwise
- write our recursive solver.

In [32]:
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]]

we use 0 for the empty space, 1-9 for the correspoding digits

the grid is a list of 9 rows and every row is a list of 9 numbers
hence grid[y][x] is the item in row y at colum x.

In [2]:
grid[2][1]

9

the built-in printing function doesn't look very nice

In [3]:
print(grid)

[[5, 3, 0, 0, 7, 0, 0, 0, 0], [6, 0, 0, 1, 9, 5, 0, 0, 0], [0, 9, 8, 0, 0, 0, 0, 6, 0], [8, 0, 0, 0, 6, 0, 0, 0, 3], [4, 0, 0, 8, 0, 3, 0, 0, 1], [7, 0, 0, 0, 2, 0, 0, 0, 6], [0, 6, 0, 0, 0, 0, 2, 8, 0], [0, 0, 0, 4, 1, 9, 0, 0, 5], [0, 0, 0, 0, 8, 0, 0, 7, 9]]


cheat: I looked up "print matrix in python" on google and foud a simple solution on stackoverflow.

In [4]:
import numpy

In [5]:
print(numpy.array(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


Alternatively we can define a specialized print function.

In [6]:
SIZE = 9 # always define constants as variables!

In [7]:
def print_grid() :
    global grid
    for row in range(SIZE) :
        for col in range(SIZE) :
            if grid[row][col]==0 :
                print(".",end=" ")
            else :
                print(grid[row][col],end=" ")
        print()

In [8]:
print_grid()

5 3 . . 7 . . . . 
6 . . 1 9 5 . . . 
. 9 8 . . . . 6 . 
8 . . . 6 . . . 3 
4 . . 8 . 3 . . 1 
7 . . . 2 . . . 6 
. 6 . . . . 2 8 . 
. . . 4 1 9 . . 5 
. . . . 8 . . 7 9 


possible(y,x,n) returns true if it is possible to put n on grid[y][x] false, otherwise

In [23]:
def possible(y,x,n) :
    # check the row
    for i in range(0,SIZE) :
        if grid[y][i]==n :
            return False
    # check the column
    for i in range(0,SIZE) :
        if grid[i][x]==n :
            return False
    # check the small square
    # we calculate the origin of the small square of the current 
    # position
    y0 = (y//3)*3
    x0 = (x//3)*3
    # check all the 9 positions in the current square
    for i in range(0,3) :
        for j in range(0,3) :
            if grid[y0+i][x0+j]==n :
                return False
    # checked everything, it is possible
    return True

In [17]:
def print_coord() :
    for row in range(SIZE) :
        for col in range(SIZE) :
            row0 = (row//3)*3
            col0 = (col//3)*3
            print(f"({row0},{col0})",end="\t")
        print()

To explain the computation of x0,y0 in ``possible``

In [58]:
print_coord()

(0,0)	(0,0)	(0,0)	(0,3)	(0,3)	(0,3)	(0,6)	(0,6)	(0,6)	
(0,0)	(0,0)	(0,0)	(0,3)	(0,3)	(0,3)	(0,6)	(0,6)	(0,6)	
(0,0)	(0,0)	(0,0)	(0,3)	(0,3)	(0,3)	(0,6)	(0,6)	(0,6)	
(3,0)	(3,0)	(3,0)	(3,3)	(3,3)	(3,3)	(3,6)	(3,6)	(3,6)	
(3,0)	(3,0)	(3,0)	(3,3)	(3,3)	(3,3)	(3,6)	(3,6)	(3,6)	
(3,0)	(3,0)	(3,0)	(3,3)	(3,3)	(3,3)	(3,6)	(3,6)	(3,6)	
(6,0)	(6,0)	(6,0)	(6,3)	(6,3)	(6,3)	(6,6)	(6,6)	(6,6)	
(6,0)	(6,0)	(6,0)	(6,3)	(6,3)	(6,3)	(6,6)	(6,6)	(6,6)	
(6,0)	(6,0)	(6,0)	(6,3)	(6,3)	(6,3)	(6,6)	(6,6)	(6,6)	


Maybe it helps to look atthe case for one dimension only

In [21]:
def one_coord() :
    for i in range(SIZE) :
        print(f"i={i},i//3={i//3},(i//3)*3={(i//3)*3}\t")

In [22]:
one_coord()

i=0,i//3=0,(i//3)*3=0	
i=1,i//3=0,(i//3)*3=0	
i=2,i//3=0,(i//3)*3=0	
i=3,i//3=1,(i//3)*3=3	
i=4,i//3=1,(i//3)*3=3	
i=5,i//3=1,(i//3)*3=3	
i=6,i//3=2,(i//3)*3=6	
i=7,i//3=2,(i//3)*3=6	
i=8,i//3=2,(i//3)*3=6	


In [10]:
possible(4,4,5)

True

In [11]:
possible(4,4,1)

False

In [9]:
possible(1,2,1)

False

In [10]:
possible(1,2,2)

True

We can implement the solver

In [48]:
def solve() :
    #print_grid()
    #input("More?")
    # look for an empty square
    for i in range(0,9) :
        for j in range(0,9) :
            if grid[i][j] == 0 :
                # found an empty square, try all digits
                for n in range(1,10) :
                    if possible(i,j,n) :
                        # we can put n here, let's do it
                        grid[i][j] = n
                        # recursively solve the remaining grid
                        solve()
                        # failed hence lets look for other options
                        grid[i][j] = 0
                # none of the numbers worked, we failed
                return
    # we didn't find an empty square, we are done
    print_grid()
    # wait for the user to press return before looking for other
    # solutions
    input("More?")

In [ ]:
How to make an empty grid.

In [49]:
def mk_empty_grid() :
    global grid
    grid=[]
    for i in range(SIZE) :
        row=[]
        for j in range(SIZE) :
            row = row+[0]
        grid=grid+[row]

In [50]:
mk_empty_grid()

In [51]:
grid

[[0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [52]:
print_grid()

. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 
. . . . . . . . . 


In [53]:
solve()

1 2 3 4 5 6 7 8 9 
4 5 6 7 8 9 1 2 3 
7 8 9 1 2 3 4 5 6 
2 1 4 3 6 5 8 9 7 
3 6 5 8 9 7 2 1 4 
8 9 7 2 1 4 3 6 5 
5 3 1 6 4 2 9 7 8 
6 4 2 9 7 8 5 3 1 
9 7 8 5 3 1 6 4 2 
More?
1 2 3 4 5 6 7 8 9 
4 5 6 7 8 9 1 2 3 
7 8 9 1 2 3 4 5 6 
2 1 4 3 6 5 8 9 7 
3 6 5 8 9 7 2 1 4 
8 9 7 2 1 4 3 6 5 
5 3 1 6 4 2 9 7 8 
6 4 8 9 7 1 5 3 2 
9 7 2 5 3 8 6 4 1 


KeyboardInterrupt: 