Sudoku solver

- how to represent the grid? x
- how to print the solution x
- is it possible to put a number on an empty square?
    possible(y,x,n) returns true if it is possible to put n on grid[y][x]
    false, otherwise
- write our recursive solver.

In [1]:
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]]

we use 0 for the empty space, 1-9 for the correspoding digits

the grid is a list of 9 rows and every row is a list of 9 numbers
hence grid[y][x] is the item in row y at colum x.

In [2]:
grid[2][1]

9

the built-in printing function doesn't look very nice

In [3]:
print(grid)

[[5, 3, 0, 0, 7, 0, 0, 0, 0], [6, 0, 0, 1, 9, 5, 0, 0, 0], [0, 9, 8, 0, 0, 0, 0, 6, 0], [8, 0, 0, 0, 6, 0, 0, 0, 3], [4, 0, 0, 8, 0, 3, 0, 0, 1], [7, 0, 0, 0, 2, 0, 0, 0, 6], [0, 6, 0, 0, 0, 0, 2, 8, 0], [0, 0, 0, 4, 1, 9, 0, 0, 5], [0, 0, 0, 0, 8, 0, 0, 7, 9]]


cheat: I looked up "print matrix in python" on google and foud a simple solution on stackoverflow.

In [4]:
import numpy

In [5]:
print(numpy.array(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


possible(y,x,n) returns true if it is possible to put n on grid[y][x] false, otherwise

In [15]:
def possible(y,x,n) :
    # check the row
    for i in range(0,9) :
        if grid[y][i]==n :
            return False
    # check the column
    for i in range(0,9) :
        if grid[i][x]==n :
            return False
    # check the small square
    # we calculate the origin of the small square of the current 
    # position
    y0 = (y//3)*3
    x0 = (x//3)*3
    # check all the 9 positions in the current square
    for i in range(0,3) :
        for j in range(0,3) :
            if grid[y0+i][x0+j]==n :
                return False
    # checked everything, it is possible
    return True

In [7]:
possible(4,4,5)

True

In [8]:
possible(4,4,1)

False

In [9]:
possible(1,2,1)

False

In [10]:
possible(1,2,2)

True

We can implement the solver

In [12]:
def solve() :
    # look for an empty square
    for i in range(0,9) :
        for j in range(0,9) :
            if grid[i][j] == 0 :
                # found an empty square, try all digits
                for n in range(1,10) :
                    if possible(i,j,n) :
                        # we can put n here, let's do it
                        grid[i][j] = n
                        # recursively solve the remaining grid
                        solve()
                        # failed hence lets look for other options
                        grid[i][j] = 0
                # none of the numbers worked, we failed
                return
    # we didn't find an empty square, we are done
    print(numpy.array(grid))
    # wait for the user to press return before looking for other
    # solutions
    input("More?")

In [13]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
More?
